language: smalltalk
sudo: false

os:
  - linux

smalltalk:
  - Pharo32-7.0
  - Pharo64-7.0

smalltalk_config:
  - .smalltalk.ston

matrix:
  fast_finish: true
  allow_failures:
    - smalltalk: Pharo32-8.0
      smalltalk_config: .smalltalk.ston
    - smalltalk: Pharo64-8.0
      smalltalk_config: .smalltalk.ston
  include:
    - smalltalk: Pharo32-8.0
      smalltalk_config: .smalltalk.ston
    - smalltalk: Pharo64-8.0
      smalltalk_config: .smalltalk.ston
